version: "3.3"
services:
  db:
    build:
      context: .
      dockerfile: ./dockerfile.db
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: test
      POSTGRES_PORT: 5432
    volumes:
    #   - ./db-data:/var/lib/postgresql/data
      - ./util/db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  api:
    depends_on: [db]
    build:
      context: .
      dockerfile: ./dockerfile.api
    restart: unless-stopped
    container_name: api
    ports:
      - 5001:5001
          